### ISSUE TITLE
Simbolo subtração com espaços adjacentes 

### ISSUE THREAD

**Issue by coreSolver44162** [renanrocha1/automato#6]
![bug subtracao](https://user-images.githubusercontent.com/21164553/41488716-bf92a4ea-70c3-11e8-906a-eb99095e502f.png)

![bug subtracao 2](https://user-images.githubusercontent.com/21164553/41488790-fbc90c88-70c3-11e8-9da2-9030b5110daf.png)

Ao fazer o teste, o programa não identificou o operador subtração, na primeira imagem, achei que era por causa do espaço entre eles, mas, ao editar o arquivo .txt e tirar o espaço ele não reconheceu identifica.

-> Não reconheceu operador subtração..

**Comment by renanrocha1** [comment]
Pegando o arquivo do txt o caracter parece com um travessão não com um sinal de menos.
Serviu para descobrir quando não há caracteres reconhecidos estava ignorando e lendo normalmente
Também tomar cuidado ao usar diretamente o bloco de notas do windows pois para mim salvou numa codificação não suportada (ANSI). Usar utf8 para testar
