### ISSUE TITLE
caso tiver digitação errada 

### ISSUE THREAD

**Issue by coreSolver44162** [renanrocha1/automato#7]
Quando digitar sem querer uma palavra reservada, ela vai ser identificada como um identificador...

![bug digitacao errada](https://user-images.githubusercontent.com/21164553/41489083-020c4104-70c5-11e8-9e5b-b1361de869fc.png)

**Comment by renanrocha1** [comment]
Nesse caso não há muito o que fazer pelo seguinte
- Identificador precisa começar por letra com no máximo 30 caracteres
- WRRITELN é exatamente esse caso
Ainda há problemas em casos como a=x, onde a e x são válidos por serem identificadores, mas a(x não deveria ser válido.
Porém = e ( ambos são caracteres especiais, hoje essa implementação considera erros somente no não reconhecimento de caracteres especiais não suportados, ou ao extraprolar algum limite, exemplo, maior número inteiro possível, máximo de 255 caracteres numa string, etc

**Comment by renanrocha1** [comment]
Pendente de conversa para discutir a abordagem de como tratar esses outros erros
